In [1]:
import pandas as pd
import numpy as np
import sys
import os

sys.path.append(os.path.abspath('../scripts/'))

In [2]:
from data_proccessor import DataProcessor

In [3]:
data = pd.read_csv(r'C:\Users\befekadum\Documents\10x acadamy\week 3\-Insurance-Claim-Analysis\data\MachineLearningRating_v3.csv',delimiter='|' )

C:\Users\befekadum\AppData\Local\Temp\ipykernel_19788\3969045969.py:1: DtypeWarning: Columns (32,37) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(r'C:\Users\befekadum\Documents\10x acadamy\week 3\-Insurance-Claim-Analysis\data\MachineLearningRating_v3.csv',delimiter='|' )

In [4]:
DataProcessor = DataProcessor(data)

In [5]:
data

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000093,31520,389,2015-04-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000094,31520,389,2015-06-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000095,31520,389,2015-08-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000096,31519,389,2014-07-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0
1000097,31519,389,2015-02-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0

In [6]:
data.dtypes

UnderwrittenCoverID           int64
PolicyID                      int64
TransactionMonth             object
IsVATRegistered                bool
Citizenship                  object
LegalType                    object
Title                        object
Language                     object
Bank                         object
AccountType                  object
MaritalStatus                object
Gender                       object
Country                      object
Province                     object
PostalCode                    int64
MainCrestaZone               object
SubCrestaZone                object
ItemType                     object
mmcode                      float64
VehicleType                  object
RegistrationYear              int64
make                         object
Model                        object
Cylinders                   float64
cubiccapacity               float64
kilowatts                   float64
bodytype                     object
NumberOfDoors               float64
VehicleIntroDate             object
CustomValueEstimate         float64
AlarmImmobiliser             object
TrackingDevice               object
CapitalOutstanding           object
NewVehicle                   object
WrittenOff                   object
Rebuilt                      object
Converted                    object
CrossBorder                  object
NumberOfVehiclesInFleet     float64
SumInsured                  float64
TermFrequency                object
CalculatedPremiumPerTerm    float64
ExcessSelected               object
CoverCategory                object
CoverType                    object
CoverGroup                   object
Section                      object
Product                      object
StatutoryClass               object
StatutoryRiskType            object
TotalPremium                float64
TotalClaims                 float64
dtype: object

data cleaning

In [7]:
DataProcessor.missing_data_summary()

                         Missing Count  Percentage (%)
NumberOfVehiclesInFleet        1000098      100.000000
CrossBorder                     999400       99.930207
CustomValueEstimate             779642       77.956560
WrittenOff                      641901       64.183810
Converted                       641901       64.183810
Rebuilt                         641901       64.183810
NewVehicle                      153295       15.327998
Bank                            145961       14.594670
AccountType                      40232        4.022806
Gender                            9536        0.953507
MaritalStatus                     8259        0.825819
mmcode                             552        0.055195
VehicleType                        552        0.055195
make                               552        0.055195
VehicleIntroDate                   552        0.055195
NumberOfDoors                      552        0.055195
bodytype                           552        0.055195
kilowatts                          552        0.055195
cubiccapacity                      552        0.055195
Cylinders                          552        0.055195
Model                              552        0.055195
CapitalOutstanding                   2        0.000200

In [8]:
DataProcessor.handle_missing_data()

c:\Users\befekadum\Documents\10x acadamy\week 3\-Insurance-Claim-Analysis\scripts\data_proccessor.py:61: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[column].fillna(self.data[column].mean(), inplace=True)
c:\Users\befekadum\Documents\10x acadamy\week 3\-Insurance-Claim-Analysis\scripts\data_proccessor.py:79: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  self.data[column].fillna(self.data[column].mode()[0], inplace=True)

Warning: Strategy 'mean' is not applicable for non-numerical column 'Bank'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'AccountType'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'MaritalStatus'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'Gender'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'VehicleType'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'make'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'Model'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'bodytype'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'VehicleIntroDate'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'CapitalOutstanding'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'NewVehicle'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'WrittenOff'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'Rebuilt'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'Converted'. Defaulting to 'mode'.
Warning: Strategy 'mean' is not applicable for non-numerical column 'CrossBorder'. Defaulting to 'mode'.

In [9]:
DataProcessor.get_processed_data()

,UnderwrittenCoverID,PolicyID,TransactionMonth,IsVATRegistered,Citizenship,LegalType,Title,Language,Bank,AccountType,...,ExcessSelected,CoverCategory,CoverType,CoverGroup,Section,Product,StatutoryClass,StatutoryRiskType,TotalPremium,TotalClaims
0,145249,12827,2015-03-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
1,145249,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,21.929825,0.0
2,145249,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Windscreen,Windscreen,Windscreen,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
3,145255,12827,2015-05-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,512.848070,0.0
4,145255,12827,2015-07-01 00:00:00,True,,Close Corporation,Mr,English,First National Bank,Current account,...,Mobility - Metered Taxis - R2000,Own damage,Own Damage,Comprehensive - Taxi,Motor Comprehensive,Mobility Metered Taxis: Monthly,Commercial,IFRS Constant,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1000093,31520,389,2015-04-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000094,31520,389,2015-06-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000095,31520,389,2015-08-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Third Party,Third Party,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,347.235175,0.0
1000096,31519,389,2014-07-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0
1000097,31519,389,2015-02-01 00:00:00,False,ZW,Individual,Mr,English,ABSA Bank,Savings account,...,No excess,Passenger Liability,Passenger Liability,Comprehensive - Taxi,Motor Comprehensive,Mobility Commercial Cover: Monthly,Commercial,IFRS Constant,2.315000,0.0

In [10]:
data.to_csv(r'C:\Users\befekadum\Documents\10x acadamy\week 3\-Insurance-Claim-Analysis\data\cleaned_data.csv')